import Config

# Configure your database
config :community_health, CommunityHealth.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "community_health_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :community_health, CommunityHealthWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: 4000],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "JrjmDbDasXqR3jsBY4MNMYmEs5/L/4goTFphFNpHseus86NiNtyXe6kSHXTPucyj",
  watchers: []

# These map the env vars docker-compose.yml sets for the "app" service onto
# config, mirroring how Underlined's api/config/runtime.exs does it.
if database_url = System.get_env("DATABASE_URL") do
  config :community_health, CommunityHealth.Repo, url: database_url
end

if secret_key_base = System.get_env("SECRET_KEY_BASE") do
  config :community_health, CommunityHealthWeb.Endpoint, secret_key_base: secret_key_base
end

if phx_host = System.get_env("PHX_HOST") do
  config :community_health, CommunityHealthWeb.Endpoint, url: [host: phx_host]
end

if port = System.get_env("PORT") do
  config :community_health, CommunityHealthWeb.Endpoint,
    http: [ip: {0, 0, 0, 0}, port: String.to_integer(port)]
end

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Do not include metadata nor timestamps in development logs
config :logger, :console, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime
